### ISSUE TITLE
Are demos meant to be non-deterministic?

### ISSUE THREAD

**Issue by nmstoker** [resemble-ai/Resemblyzer#12]
When running demo 04 I get different results each time.  I appreciate that with demo 05, it randomly selects from the 12 real samples so the outcome would vary, but I would have expected that the other demos would be deterministic.  What's the expected behaviour in this regard?

Also in demo 04, I needed to apply a sort to the glob results or it would be unable to show any pattern (it appeared to be linking the gender markers arbitrarily).  I'm running Linux, so the glob behaviour this way may differ to Windows. Even when I've done that though, the results are different (although they do segregate the voice samples by gender then).

I can include some screenshots later if it's helpful.

**Comment by CorentinJ** [comment]
The non-deterministic part is UMAP. The embeddings are always the same, but the projections/clustering can vary depending on the seed of UMAP.

**Comment by nmstoker** [comment]
Ah, I see. Thanks for clarifying.
