### ISSUE TITLE
Demo 01: Similarity

### ISSUE THREAD

**Issue by sberryman** [resemble-ai/Resemblyzer#13]
I've run the similarity demo against my model trained on English speakers using 768 hidden layers and embedding size.

I found it very interesting to see the cross similarity matrix at different checkpoints. Your model appears to do a better job for utterance similarity. Do you think this is due to the fact I just need to train the model for longer? I'm going to continue training the model for at least another week. 

Note: I've changed the histogram and matrix range to [0, 1]

## Model included in this repository
Utterance Median: 0.52 / 0.89
![similarity_default](https://user-images.githubusercontent.com/324437/67234212-94c73400-f3f9-11e9-987d-83d8708e6491.png)

## 300k steps
Utterance Median: 0.21 / 0.82
![similarity_768_300k](https://user-images.githubusercontent.com/324437/67234239-a3155000-f3f9-11e9-8cca-ea5334a7af35.png)

## 500k steps
Utterance Median: 0.29 / 0.82
![similarity_768_500k](https://user-images.githubusercontent.com/324437/67234261-ae687b80-f3f9-11e9-8392-56ee03da20a4.png)

## 1M steps
Utterance Median: 0.35 / 0.83
![similarity_768_1M](https://user-images.githubusercontent.com/324437/67234284-b7f1e380-f3f9-11e9-807e-2061d68e3285.png)

## 1.3M steps
Utterance Median: 0.33 / 0.81
![similarity_768_1 3M](https://user-images.githubusercontent.com/324437/67234317-c4763c00-f3f9-11e9-88ba-e3bcf2f2a1cf.png)

## 1.725M steps
Utterance Median: 0.33 / 0.80
![similarity_768_1 725M](https://user-images.githubusercontent.com/324437/67234350-d22bc180-f3f9-11e9-88a6-b37cbd6df0f4.png)

## Multiple languages 525k steps
Utterance Median: 0.31 / 0.85
_This model has 1024 hidden and embedding size._
![similarity_1024](https://user-images.githubusercontent.com/324437/67234057-42861300-f3f9-11e9-8ff1-9a01b0c91c21.png)

**Comment by CorentinJ** [comment]
Quite surprising to see the similarity values for distinct utterances *increasing* as the model progresses. I guess its decision boundary is becoming sharper over time.

**Comment by sberryman** [comment]
Good to know you were also surprised. Based on what I see for my model and your 256/256 model is that I need to train this for significantly longer, correct?

**Comment by CorentinJ** [comment]
Use a bigger dataset for fair comparison. I had made [this plot](https://github.com/resemble-ai/Resemblyzer/blob/master/plots/sim_matrix_3.png) by considering the entirety of the test set IIRC (the code is modulable to handle another number of speakers).

The error rate is what you should be concerned about; i.e. if the two distributions are linearly separable (they are in the example with 10 speakers but not with 40 speakers in the plot I linked) and by how much they overlap. From the examples you've shown here your model doesn't seem to be performing any worse than mine so I'm not sure why you're concerned.

**Comment by sberryman** [comment]
Sorry, didn't mean to close it quite yet.

Was that plot using the full test-other or test-clean+test-other?

**Comment by CorentinJ** [comment]
I think it was test-other, but the original one from the librispeech page. The sets I've included are only partially complete.

**Comment by CorentinJ** [comment]
Might have been test-clean or dev-clean actually, because the "other" sets have only 33 speakers.

edit: I've fixed [this readme](https://github.com/resemble-ai/Resemblyzer/blob/master/audio_data/README.md)

**Comment by sberryman** [comment]
sim_matrix_3 which you linked to is showing 33 speakers in the plot and speaker ids look to align with test-other.

I took the full test-other and grabbed the first 10 utterances per speaker. The "all utterances" is the entire test-other, meaning every utterance for each speaker is plotted (2,939 total utterances)

On a very quick glance and 33 people with 10 utterances per speaker, there is almost no difference between the two models (based on the UMAP projection) The 768 model does a slightly better job separating the speakers. It was interesting to see the clusters when ALL utterances for each speaker were plotted.

## Your model
![similarity_default_33](https://user-images.githubusercontent.com/324437/67239700-a4984580-f404-11e9-802c-b64eab4e89af.png)
![projection_default_33_10](https://user-images.githubusercontent.com/324437/67243573-ba116d80-f40c-11e9-9f8c-c6d3c33b946a.png)
![projection_default_33_all](https://user-images.githubusercontent.com/324437/67243847-5a679200-f40d-11e9-956a-e34543c0633e.png)

## 768 model
![similarity_768_33](https://user-images.githubusercontent.com/324437/67239708-a82bcc80-f404-11e9-8d9e-7424fc0e7a8f.png)
![projection_768_33_10](https://user-images.githubusercontent.com/324437/67244109-dd88e800-f40d-11e9-9ade-0433fa8dcb80.png)
![projection_768_33_all](https://user-images.githubusercontent.com/324437/67244066-c77b2780-f40d-11e9-91bc-c3897441bc5b.png)
![projection_768_33_all_legend](https://user-images.githubusercontent.com/324437/67244728-34db8800-f40f-11e9-8c66-15f31feb58b5.png)

**Comment by CorentinJ** [comment]
Very nice, I could definitely make your model the default.

**Comment by CorentinJ** [comment]
Note that clusters of the same color that are close to each other are from the same speaker but from different books.

**Comment by sberryman** [comment]
Interesting, I wasn't sure right away if they were the same speaker as it is hard to generate 30+ colors that are visually distinct.

**Comment by sberryman** [comment]
For fun I tried to plot test-other and dev-other at the same time.

## Default model
![projection_default_dev-test_10](https://user-images.githubusercontent.com/324437/67245534-14143200-f411-11e9-9733-8dc2caf227dc.png)

## 768
![projection_768_dev-test_10](https://user-images.githubusercontent.com/324437/67245529-11194180-f411-11e9-85ec-a62b7d198cad.png)

**Comment by CorentinJ** [comment]
See the plot below where I was clustering by book rather than by speaker:
![image](https://user-images.githubusercontent.com/12038136/67245591-a2fa6c00-f45c-11e9-8ca7-4a9f21cb4e3d.png)
You can see the yellow squares in the diagonal, their size is the number of book for the given speaker.

**Comment by sberryman** [comment]
I had done a few plots by book by accident before I realized I needed to change speakers list.

```python
speakers = list(map(lambda wav_fpath: wav_fpath.parent.parent.stem, wav_fpaths))
```

**Comment by sberryman** [comment]
And finally here are the plots of dev & test including both clean and other.I'm assuming there isn't an overlap between speakers in the dev & test sets so this should be 146 speakers with 10 utterances each.

## Default
![image](https://user-images.githubusercontent.com/324437/67246257-cb5d7880-f412-11e9-8a0a-6a71f809c117.png)
![image](https://user-images.githubusercontent.com/324437/67247989-c8b15200-f417-11e9-9fea-0b03fed42dcc.png)

## 768
![image](https://user-images.githubusercontent.com/324437/67246912-aff36d00-f414-11e9-8265-ccbcfa321625.png)
![image](https://user-images.githubusercontent.com/324437/67248002-d1a22380-f417-11e9-824c-f7c697ba9cac.png)

_Edit: Added all utterances for default and 768 models._

**Comment by CorentinJ** [comment]
You might be interested to know that passing `min_dist=1` to UMAP will disable its tendency to create clusters, giving you an "unbiased" view of the manifold.

**Comment by sberryman** [comment]
Thanks!! I’ll try that out shortly

**Comment by sberryman** [comment]
Finally back, I've let the model continue training up to 2.38M steps now and it is clearly getting better.

## 10 speakers
#### 1.75M steps
![image](https://user-images.githubusercontent.com/324437/67785828-1850d880-fa2b-11e9-95d6-65a755efc2ef.png)
#### 2.38M steps
![image](https://user-images.githubusercontent.com/324437/67785872-27d02180-fa2b-11e9-88fa-391b5e5599e7.png)

## 33 speakers
#### 1.75M
![image](https://user-images.githubusercontent.com/324437/67786031-6ebe1700-fa2b-11e9-879f-d512559b65e1.png)
#### 2.38M
![image](https://user-images.githubusercontent.com/324437/67786056-7a114280-fa2b-11e9-8f1b-3c95b911803b.png)

# Minimum distance = 1
## 10 speakers
#### Default
![image](https://user-images.githubusercontent.com/324437/67787432-cfe6ea00-fa2d-11e9-81c3-9424a6310942.png)
#### 2.38M
![image](https://user-images.githubusercontent.com/324437/67787454-da08e880-fa2d-11e9-8fa8-f90cbeb4f6aa.png)

## 33 speakers
#### Default
![image](https://user-images.githubusercontent.com/324437/67787494-ec832200-fa2d-11e9-82ce-c02dc41fcf8e.png)
#### 2.38M
![image](https://user-images.githubusercontent.com/324437/67787657-2ce2a000-fa2e-11e9-9d8e-b995b54893a5.png)

### n_components=3
#### Default
![image](https://user-images.githubusercontent.com/324437/67788997-7fbd5700-fa30-11e9-8ee6-4848dc63b973.png)
#### 2.38M
![image](https://user-images.githubusercontent.com/324437/67789027-8a77ec00-fa30-11e9-95a5-152b463fedde.png)


## Notes
![image](https://user-images.githubusercontent.com/324437/67786308-e4c27e00-fa2b-11e9-8806-e7e12006bee3.png)
1.75M steps had an EER of about 0.00669
2.38M steps had an EER of about 0.00392

It was neat to see the embeddings projected into 3D space.

**Comment by sberryman** [comment]
Question on the similarity charts for 33 speakers.

The median value of other speakers is moving towards the median of same speakers. It also appears that the values for same and different speakers are moving closer towards their median. Would this be an indication that the model is getting better at determining the boundary?

-------------

Without revealing any proprietary information, can you share how the similarity plots compare to internal models?

-------------
I'm getting close to running my model against ~7,000 hours of local news broadcasts from 320 stations across the USA.

**Comment by CorentinJ** [comment]
Maybe, technically if you read the ge2e paper you should use the weight and bias parameters that I added to the model to figure out the boundary, but I never really understood how that worked.

Well we haven't trained a new version _yet_, it's actually something I am going to be working on now. I'm planning to use different mel parameters and I'll try to see if I can find more speakers to train on. Mostly I'll figure out a way to increase the batch size without having to deal with cubic complexity on the side of the similarity matrix. I thought of a way for that and it should be fairly straightforward.

**Comment by sberryman** [comment]
Good to know, will be interesting to hear how that goes if you are able to share any of the training results.

I found Common Voice from Mozilla to be the biggest and easiest dataset to add. TEDLIUM I haven't merged in yet as they have multiple speakers per talk/presentation. TEDLIUM would add roughly 1,800-1,900 new speakers.

For increasing the batch size are you increasing the number of speakers or number of utterances per speaker? Have you played around with increasing the number of speakers while reducing the number of utterances?

**Comment by CorentinJ** [comment]
The number of speakers. I'll probably train on a batch size of 512 speakers or so, but I'll build individual similarity matrices for groups of 64 speakers every time to avoid the cubic complexity

edit: this was naive, the complexity is only quadratic w.r.t. the number of speakers and it's still small w.r.t. the time of the forward backward pass for batch sizes under ~1000

**Comment by sberryman** [comment]
Here is another small dataset I'm going to merge in and resume training from 2.4M

The DARPA TIMIT Acoustic-Phonetic Continuous Speech Corpus
http://academictorrents.com/details/34e2b78745138186976cbc27939b1b34d18bd5b3

> TIMIT contains a total of 6300 sentences, 10 sentences spoken by each of 630 speakers from 8 major dialect regions of the United States.

**Comment by sberryman** [comment]
I added the 630 speakers bringing the total up to 28,062 speakers. I also changed the batch size from 64 to 96 which about the max I could take it on my 1080TI. That has taken my mean step time up to 1,476ms.

I'm not sure why the NVMe drive isn't loading more quickly.
```shell
Step 2405700   Loss: 0.0116   EER: 0.0037   Step time:  mean:  1476ms  std:   295ms

Average execution time over 10 steps:
  Blocking, waiting for batch (threaded) (10/10):  mean:  139ms   std:  116ms
  Data to cuda (10/10):                            mean:    4ms   std:    0ms
  Forward pass (10/10):                            mean:  386ms   std:    2ms
  Loss (10/10):                                    mean:   36ms   std:    1ms
  Backward pass (10/10):                           mean:  141ms   std:    7ms
  Parameter update (10/10):                        mean:  748ms   std:    2ms
  Extras (visualizations, saving) (10/10):         mean:   26ms   std:   74ms
```

Performance:
```shell
sudo hdparm -Tt --direct /dev/nvme0n1

/dev/nvme0n1:
 Timing O_DIRECT cached reads:   2176 MB in  2.00 seconds = 1088.56 MB/sec
 Timing O_DIRECT disk reads: 5308 MB in  3.00 seconds = 1768.59 MB/sec
```

Not overly concerned about that though. Much more interested in how you are scaling up to a batch size of 512 :grin:

This is just FYI

**Comment by CorentinJ** [comment]
You can solve both these problems, but it requires good engineering:
1. You can increase your batch size arbitrarily by doing multiple forward passes before the backward pass, and the gradients will accumulate
2. You can reuse utterances by keeping them in a pool to avoid reloading them from disk. If you compare them against different utterances, it's still a new batch. E.g. if you have utterances A, B, C and D, you can have batches [A, B] and [C, D] but also [A, C] and [B, D] etc... 
3. You can be more efficient by using every partial utterance of an utterance you load. 

Personally I intend to have a buffer of utterances in memory for every speaker. I did the maths, and for an average of 10 utterances in RAM per speaker I would use approx. 10gb of RAM. This is the most efficient method imo, and it also allows you to sample data while being equal in the amount of data sampled per speaker. That might help with some bias. I wish I could also do something about gender imbalance in the datasets, but few of them have labels.

**Comment by CorentinJ** [comment]
Oh and you can halve your memory usage above if you use [as_strided](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.lib.stride_tricks.as_strided.html).

**Comment by sberryman** [comment]
Well that was very helpful information!

1. This should be trivial to implement, working on that now.
2. Well this is a neat approach
3. As opposed to the random (partial) offset for longer utterances? Also a really good idea

Personally a fan of the large buffer of utterances as well, I'm assuming you are only going to buffer `n_frames` length from each utterance?

**Comment by CorentinJ** [comment]
I'm going to buffer 10 * `partial_n_frames` of each utterance. On a second thought it's better if training partial utterances don't overlap, so forget about the stride tricks.

**Comment by sberryman** [comment]
After more exploration I now see what you are talking about for cubic complexity when calculating the loss. Since I'm performing loss on the GPU there isn't enough memory which means I have to compute it on each mini batch.

This is nowhere near my expertise, still assuming waiting to compute `model.do_gradient_ops(); optimizer.step()` is accumulating the gradients? Based on what I've read in blog posts, it is still accumulating.

Edit: I've also found that using `pin_memory=True` for the dataset loader has drastically improved performance loading data.

```shell
Step 2448060   Loss: 0.0104   EER: 0.0033   Step time:  mean:  1274ms  std:     9ms

Average execution time over 10 steps:
  Blocking, waiting for batch (threaded) (10/10):  mean:    3ms   std:    1ms
  Data to cuda (10/10):                            mean:    4ms   std:    0ms
  Forward pass (10/10):                            mean:  387ms   std:    2ms
  Loss (10/10):                                    mean:   59ms   std:    2ms
  Backward pass (10/10):                           mean:  814ms   std:    3ms
  Parameter update (10/10):                        mean:    4ms   std:    0ms
  Extras (visualizations, saving) (10/10):         mean:    3ms   std:    9ms
```

**Comment by sberryman** [comment]
Decided to start working on acquiring more training data. Since I knew some of the TEDLIUM (release 3) presentations contained more than 1 speaker I started with that dataset.

There are 1,925 presentations and I broke them into utterances based on the provided stm files (which looks like they used Kaldi to acquire)

Then I used all the partials for all utterances in a presentation and projected used the defaults for UMAP. Finally used DBSCAN from sklearn to label the clusters. If all of the partials for a single utterance were not the same I placed those into a "mixed" result set and based on initial observations it did a phenomenal job. 100% of the mixed labels did include more than 1 speaker.

Results:
- Single cluster: 1,296
- Multiple clusters: 623
- Zero clusters: 6

I'm now going to go through the 623 and quickly pull out the host (Chis Anderson). Then I'll manually go through the remaining presentations that have more than 1 cluster with the host removed. There is such a wide variety of accents that it should be a very valuable dataset.

## Examples
![image](https://user-images.githubusercontent.com/324437/68075202-dba21b80-fd61-11e9-9800-0b4269dcedad.png)
![image](https://user-images.githubusercontent.com/324437/68075207-ed83be80-fd61-11e9-838d-5a7e93d58b3b.png)
![image](https://user-images.githubusercontent.com/324437/68075223-376ca480-fd62-11e9-935b-12081f90a00f.png)
![image](https://user-images.githubusercontent.com/324437/68075248-831f4e00-fd62-11e9-96b4-f2ea93a8e474.png)
![image](https://user-images.githubusercontent.com/324437/68075283-ce396100-fd62-11e9-87ee-110388df3803.png)

## Music
This was fun as it was never trained using songs/singing

### One Guy, 43 voices
Source: https://www.youtube.com/watch?v=jPoLeJJsbCw
![image](https://user-images.githubusercontent.com/324437/68075636-9aad0580-fd67-11e9-9022-622fff843d2d.png)

### The Beatles - I Feel Fine
Source: https://www.youtube.com/watch?v=WrAV5EVI4tU
![image](https://user-images.githubusercontent.com/324437/68075706-84537980-fd68-11e9-8851-7986d0f90401.png)

### Michael Jackson - I Just Cant Stop Loving You
Source: https://www.youtube.com/watch?v=A1MGCNYU4WE
![image](https://user-images.githubusercontent.com/324437/68075743-3d19b880-fd69-11e9-98f0-f06b1284dbae.png)

**Comment by CorentinJ** [comment]
The tedlium plots are very interesting, but I wouldn't be motivated enough to manually sort out the speakers 😅. Have you considered comparing the embeddings across differents interviews to build a database of speakers where you merge together voices that are close enough? 

I guess the more data you get, the more likely you are to have two different IDs for the same speaker. It's probably not something that would hurt the training much if it doesn't occur that often though.

On my end I've been reimplementing the model and here is what came out of it:
- The thing about cubic complexity is a stupid error that I made 1 year ago as well: the forward and backward passes are the slow parts of the training, not computing the similarity matrix. I jumped to that conclusion because I forgot to put `torch.cuda.synchronize()` before my profiler ticks. While the compute time of the similarity matrix is indeed `O(n_spk² * n_utt)`, it is still minor with respect to the time of the forward & backward pass. Until I get my hands on GPUs with 200gb of VRAM, I believe I'm safe. The total step time is linear in respect to the number of speakers per batch, so there is a real gain in trying to compute a similarity matrix as large as possible given your VRAM. I don't see an easy way to do this with accumulation steps, but with multiple GPUs it should be straightforward.
- The size of the LSTM hidden size is the other factor that has a huge influence on the step time (as you've noticed yourself). I've tried to see what a projection layer inbetween LSTM layers would give (as in the GE2E paper), but the speedup is minor and the learning slower.
- I believe that removing the relu at the end of the forward pass makes convergence faster. Embeddings are then no longer strictly positive. Note that this relu is something I had added by mistake and decided to keep, it's not in the GE2E paper.
- Here's how I compute the similarity matrix now, it's slightly faster than what is currently in my sv2tts repo:
```
        sim_matrix = torch.zeros(n_speakers, n_utterances, n_speakers).to(embeds.device)
        eye = np.eye(n_speakers, dtype=np.int)
        mask = np.where(1 - eye)
        sim_matrix[mask[0], :, mask[1]] = (embeds[mask[0]] * centroids_incl[mask[1]]).sum(dim=2)
        mask = np.where(eye)
        sim_matrix[mask[0], :, mask[1]] = (embeds * centroids_excl).sum(dim=2)
```
- Here are my times with 128 speakers and 10 utterances per batch, and a hidden size of 768 in the lstm layers (embedding size is still 256) on a GTX Quadro 6000:
```
Average execution time over 10 steps:
  Retrieving batch:  mean:    6ms   std:    0ms
  Data to GPU:       mean:    8ms   std:    1ms
  Forward pass:      mean:  326ms   std:    3ms
  Loss compute:      mean:   31ms   std:    7ms
  Backward pass:     mean:  687ms   std:    3ms
  Optimizer step:    mean:    2ms   std:    0ms
```

**Comment by CorentinJ** [comment]
Oh and if you remove the optimizer state from pretrained models, the filesize will be 1/3rd of the original size. I distributed the package with a pretrained model of 16.7mb that could actually have been only 5.6mb...

**Comment by sberryman** [comment]
Excellent, thanks for the update!

Your profiler looks very consistent with mine now, looks like you implemented the two tiny changes that helped me speed up training. Loss running on GPU and `pin_memory=True`.

Funny enough that is the same code you had commented out for similarity matrix? You had the comment `## Even more vectorized version (slower maybe because of transpose)` I'm pretty sure I tried it and didn't really notice a difference.

I may try removing the RELU at the end of the model, other than converging faster I'm assuming it doesn't make much of a difference?

I took the time to go through 1,297 presentations for TEDLIUM and let it train on just that dataset (resuming from my model around 2.8M steps)

![image](https://user-images.githubusercontent.com/324437/68309874-f5927580-0063-11ea-9121-dba3e72d6943.png)

Now I'm going to merge TEDLIUM into the much larger training set and let that continue training for a while longer. I'm also running inference on about 1,000 hours of local news and plotting the results while creating speaker clusters. Ultimately I think I'm going to train a `uis-rnn` model using the embedding.

## Local news

![projections](https://user-images.githubusercontent.com/324437/68310140-58840c80-0064-11ea-81df-35ef6d34944b.png)
![projections](https://user-images.githubusercontent.com/324437/68310164-62a60b00-0064-11ea-8e82-d88a3f61d9d0.png)
![projections](https://user-images.githubusercontent.com/324437/68310183-6b96dc80-0064-11ea-8fe8-4a95a6e30929.png)
![projections](https://user-images.githubusercontent.com/324437/68310214-79e4f880-0064-11ea-97a4-137f0901027f.png)
![projections](https://user-images.githubusercontent.com/324437/68310252-8c5f3200-0064-11ea-9c33-42a0f2354d55.png)

**Comment by sberryman** [comment]
Also, I asked earlier but forgot...

1. Have you tried training with more speakers and fewer utterances per speaker or opposite and train on fewer speakers and more utterances per speaker?
2. Shouldn't UMAP be set to `metric='cosine'`, the default is `metric='euclidean'` or are they essentially the same because the embedding is L2 normalized?

I couldn't find a reason why they chose 10 utterances per speaker in the GE2E paper. If they did an ablation study on (1), I certainly can't find it.

**Comment by CorentinJ** [comment]
1. When you think about it, the similarity matrix replicates the process of speaker identification in practice: you have a database of utterances (9 or 10 depending on whether you compare against the same speaker) and you want to compare that against a single utterance. I would say that 10 is a good ballpark number. The training speed/VRAM usage are linear w.r.t to that value so that also gives you an upper bound. It's not a perfect answer per se but I believe their reasoning did not go much further than this.

2. This is an internal conversation I've had half a dozen of times. The times when I decided to read the UMAP documentation I must not have found my answer because I still don't know.

**Comment by CorentinJ** [comment]
I had theorized that doubling the batch size would quadruple the training efficiency, because the similarity matrix would be 4 times as big. I believe that intuition is correct, because I have reached 1% EER in only 12 hours with a batch size of 256. Insane stuff

**Comment by sberryman** [comment]
That is awesome, assuming you used 2 GPUs to double the batch size to 256?

**Comment by CorentinJ** [comment]
Yeah. Regarding your other points:

> Your profiler looks very consistent with mine now, looks like you implemented the two tiny changes that helped me speed up training. Loss running on GPU and pin_memory=True.

I haven't seen any improvement with pin_memory=True though.

> Funny enough that is the same code you had commented out for similarity matrix? You had the comment ## Even more vectorized version (slower maybe because of transpose) I'm pretty sure I tried it and didn't really notice a difference.

It's almost the same code yeah, I removed the transpose but in restrospect it was probably not slowing things much if it's implemented like in numpy where they just change the strides.

> I may try removing the RELU at the end of the model, other than converging faster I'm assuming it doesn't make much of a difference?

Well you won't have stricly positive embeddings anymore. I think that might be nice, who knows, maybe distinct voices will have a cosine similarity of 0 instead of 0.4 now. That would be more meaningful at least.

Regarding the number of utterances, I assume you're asking because Common Voice and Timit don't have many utterances per speaker? That's fine though, because you're still splitting them in partial utterances. And if you happen to have twice the same partial utterance in a batch, it's not a big deal.

**Comment by sberryman** [comment]
How hard was it to change the model to train on two GPUs? I have two 1080 TI's in this box, would be interesting to let it train for a few days across both GPUs.

**Comment by CorentinJ** [comment]
Extremely simple: you wrap it in DataParallel: `dp_model = DataParallel(model, [0, 1])` and you use the dp model for the forward pass: `embeds = dp_model(mels)` but you can keep the regular model for the similarity matrix / loss: `loss = model(embeds)`.

**Comment by sberryman** [comment]
@CorentinJ WOW, can't believe it was that easy! I can fit a max of 100 speakers per batch on a 1080TI but I dropped it down to 96 to be a multiple of 8. Not sure if that actually makes a difference though.

I'm going through the entire common voice dataset and reducing the minimum number of audio files from 12 down to 4 which should double the number of speakers.

I also changed the model to remove RELU and set the hidden size to 768 while the embedding size is 256. Looking at the embedding when hidden/embedding were both 768 I noticed a lot of the (embedding) values were zero. The size of the embedding layer doesn't seem to adjust the training time a whole lot, I can't decide whether to keep it at 256 or bump it to 512.

**Comment by CorentinJ** [comment]
You should keep the embedding layer to 256, more seems excessive.

**Comment by CorentinJ** [comment]
Something you might find interesting: a peek at the similarity matrix during training. It looks like I might be headed off to having 0 as cutoff value, which is really nifty.

![image](https://user-images.githubusercontent.com/12038136/68421213-1b239a00-019e-11ea-8a5d-d697b5ad21fe.png)

**Comment by sberryman** [comment]
Great news! Out of curiosity, what datasets are you training on?

**Comment by CorentinJ** [comment]
Vox1 & 2 and LibriTTS for now. I had plans to include Common Voice like you did, and I think that will be enough. There's a lot of speakers on Common Voice already.

**Comment by sberryman** [comment]
Thanks for letting me know all the changes you've made on your end. I've got a new model training now with 42,842 speakers, 768 hidden and 256 embedding size. Unfortunately I was capped at 160 speakers for batch size but it is running on two GPUs!

#### Profiler
```shell
Average execution time over 10 steps:
  Blocking, waiting for batch (threaded) (10/10):  mean:    5ms   std:    0ms
  Data to cuda (10/10):                            mean:    7ms   std:    0ms
  Forward pass (10/10):                            mean:  347ms   std:   17ms
  Loss (10/10):                                    mean:   76ms   std:   37ms
  Backward pass (10/10):                           mean:  784ms   std:   34ms
  Parameter update (10/10):                        mean:    4ms   std:    0ms
  Extras (visualizations, saving) (10/10):         mean:    0ms   std:    0ms
```

#### GPUs
```shell
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:17:00.0 Off |                  N/A |
| 67%   69C    P2   259W / 280W |  10747MiB / 11178MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:65:00.0 Off |                  N/A |
| 57%   67C    P2   294W / 280W |   8827MiB / 11175MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      4509      C   python                                     10737MiB |
|    1      4509      C   python                                      8817MiB |
+-----------------------------------------------------------------------------+
```

Looking forward to seeing what this looks like tomorrow morning and how warm my office gets!
![Screen Shot 2019-11-07 at 1 19 17 PM](https://user-images.githubusercontent.com/324437/68428522-3623e900-0161-11ea-982f-91f27faa5c65.png)

**Comment by sberryman** [comment]
Very jealous of your 32 GB VRAM per GPU though. 

## Progress (50k steps)
![Screen Shot 2019-11-08 at 6 52 46 AM](https://user-images.githubusercontent.com/324437/68485562-65376a80-01f4-11ea-8d65-c12a9b0973ed.png)

<img width="470" alt="Screen Shot 2019-11-08 at 6 53 59 AM" src="https://user-images.githubusercontent.com/324437/68485681-94e67280-01f4-11ea-872f-e14ba14f16b4.png">

**Comment by CorentinJ** [comment]
It's 24gb but yeah, perks of working at Resemble 😀

**Comment by sberryman** [comment]
Let it train over the weekend and am up to ~255,000 steps w/ EER ~0.00314. Still have some poor separation but hit low EER MUCH MUCH faster than w/ batch size of 64. How is progress on your side?

![image](https://user-images.githubusercontent.com/324437/68598876-72eb2b00-0454-11ea-877c-6c433be662ef.png)

**Comment by sberryman** [comment]
Have you thought about changing `RandomCycler` out for a cycler that takes into account similarity? My assumption is that every N steps I could compute a massive similarity matrix and place the most similar speakers into the same batch. Not sure how much of a difference that would make but I would do it "offline" on another computer updating a JSON file on a shared drive. Would be easy to check the file modification date on the training computer and simply reload it adjusting the ideal speakers per batch. 

May be overkill and just floating the idea before I spend time on it. I feel like that would help the model improve the overlapping clusters I'm seeing right now.

**Comment by sberryman** [comment]
Stopped training at ~463k steps. Cutoff is getting closer to zero, were you able to hit zero in your training?

## 10 speakers
![image](https://user-images.githubusercontent.com/324437/68888827-899db600-06d0-11ea-865d-a87894ff830f.png)

### Utterance
Same - Median: 0.7987398505210876
Different - Median: 0.14621394872665405

### Speaker
Same - Median: 0.9421260356903076
Different - Median: 0.17534589767456055

##  33 speakers
![image](https://user-images.githubusercontent.com/324437/68888737-59eeae00-06d0-11ea-9b4c-1d820eaab7ff.png)

### Utterance
Same - Median: 0.7588032484054565
Different - Median: 0.12408770620822906

### Speaker
Same - Median: 0.9450216889381409
Different - Median: 0.15581101179122925

**Comment by sberryman** [comment]
I’m up to ~680k steps and still don’t have very defined clusters. To be fair I made a change at about 480k steps. I changed to 5 utterances per speaker while doubling the number of speakers per batch and it has made a very strong shift to lower EER. At this point I feel like the number of speakers per batch is the most important factor. 

You haven’t shared any updates recently but I would encourage you to double speakers per batch and reduce utterances per speaker in half to 5.

**Comment by CorentinJ** [comment]
I can't say for sure that you're not getting a biased value of the EER with that. If it has made a shift to lower the eer as soon as you changed that parameter then the change is meaningless. There's no validation procedure implemented so that doesn't help. Why do you want to bring the EER this low anyway?

**Comment by sberryman** [comment]
Sorry, should have included a screen shot. I don't think it looks biased and I'm not trying to bring it low as much as I'm trying to get it better at creating clusters with a larger speaker pool. I don't have the GPU memory available you do and from all the experimenting with larger speakers per mini-batch it looks like the bigger the better. Although I guess that statement is meaningless until I run an actual test.

![image](https://user-images.githubusercontent.com/324437/69061009-3c219180-09cd-11ea-8412-001fc4dd0568.png)

**Comment by sberryman** [comment]
Loss/EER explosion. Have you seen this happen during your training?

![image](https://user-images.githubusercontent.com/324437/69373890-b7977300-0c59-11ea-88c8-3d7289d37abe.png)

```shell
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/rnn.py:522: RuntimeWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
  self.dropout, self.training, self.bidirectional, self.batch_first)
..........
Step 926800   Loss: 0.0254   EER: 0.0019   Step time:  mean:  1289ms  std:   208ms
Drawing and saving projections (step 926800)
Saving the model (step 926800)
..........
Step 926900   Loss: 2.4492   EER: 0.0945   Step time:  mean:  1287ms  std:   214ms
Drawing and saving projections (step 926900)
Saving the model (step 926900)
```

**Comment by CorentinJ** [comment]
Nope

**Comment by sberryman** [comment]
922,500 steps using 264 speakers per batch with 5 utterances per speaker

## 10 speakers
![similarity_10](https://user-images.githubusercontent.com/324437/69376088-88373500-0c5e-11ea-9249-f4e1ebde0dc6.png)

### Utterance
Same - Median: 0.8071977496147156
Different - Median: 0.13521519303321838

### Speaker
Same - Median: 0.9464693665504456
Different - Median: 0.15724024176597595

##  33 speakers
![similarity_33](https://user-images.githubusercontent.com/324437/69376139-a43ad680-0c5e-11ea-9a13-a7be0fc31972.png)

### Utterance
Same - Median: 0.7776680588722229
Different - Median: 0.10720697790384293

### Speaker
Same - Median: 0.9432523250579834
Different - Median: 0.1284990757703781
