### ISSUE TITLE
Embedding is mostly zero

### ISSUE THREAD

**Issue by dodobyte** [resemble-ai/Resemblyzer#15]
I plot the embedding vector and it's mostly zeros. Is this expected?

I want to use the embedding in another [project](https://github.com/auspicious3000/autovc). I also plotted their example embeddings and those seem to be distributed significantly better.

- Embedding from this project
![](https://i.imgur.com/4noUHUg.png)

- Embeddings from AutoVC
![](https://i.imgur.com/85aVw0f.png)
![](https://i.imgur.com/C5bM7jg.png)

And here's the test code;
```python
from pathlib import Path
from resemblyzer import VoiceEncoder, preprocess_wav
import numpy as np, matplotlib.pyplot as plt

wav = preprocess_wav(Path("367-130732-0005.flac"))

encoder = VoiceEncoder()
embed = encoder.embed_utterance(wav)

plt.plot(embed, 'bo')
plt.show()
```

Am I doing something wrong? Thanks.

**Comment by CorentinJ** [comment]
Absolutely, the embeddings are sparse due to the relu at the end of the model. It doesn't make them worse, although I did remove that relu in the development branch I'm working on. Don't worry about it.
