### ISSUE TITLE
train new languages for better detection

### ISSUE THREAD

**Issue by rebotnix** [resemble-ai/Resemblyzer#18]
I would like to retrain the model for detecting italy and spanish speakers. How do you train the english model?

**Comment by rohithkodali** [comment]
hi @rebotnix ,

 you can train new models using this repository https://github.com/CorentinJ/Real-Time-Voice-Cloning
@CorentinJ  has already mentioned it in the README

**Comment by rebotnix** [comment]
I didn't see that, thanks a lot,
