### ISSUE TITLE
No figure and no sound when I run demo 02.

### ISSUE THREAD

**Issue by hkhk366** [resemble-ai/Resemblyzer#31]
![image](https://user-images.githubusercontent.com/12952110/87712651-0066e380-c777-11ea-9fb8-a7d72e1e327b.png)

Below is my environment.
![image](https://user-images.githubusercontent.com/12952110/87713291-f2fe2900-c777-11ea-9d66-8134ccd0fce9.png)
![image](https://user-images.githubusercontent.com/12952110/87713312-fee9eb00-c777-11ea-9840-f41a76d883b6.png)

All other demos work well. Just demo 2 is not working. This may be a silly question. As a beginner, after several hours of working, I still cannot fix it. Can you help me? Thank you.

**Comment by CorentinJ** [comment]
Disable this in PyCharm:
![image](https://user-images.githubusercontent.com/12038136/87713491-95cf9b00-c7aa-11ea-9636-70dc064a7908.png)

No idea why this thing is enabled by default everywhere, it's so bad

**Comment by hkhk366** [comment]
> Disable this in PyCharm:
> ![image](https://user-images.githubusercontent.com/12038136/87713491-95cf9b00-c7aa-11ea-9636-70dc064a7908.png)
> 
> No idea why this thing is enabled by default everywhere, it's so bad

Many thanks. This cost me so many hours. Now, it works, Have a nice day.

**Comment by Shridharpawar77** [comment]
I am also facing the same issue. 
I am running codes in the Jupyter notebook.
1) the plot is empty and the function is never calling the update function. 
2) so there is an empty plot and the audio is played. 

please help me fix this issue.
