### ISSUE TITLE
demo02_diarization problem

### ISSUE THREAD

**Issue by liszhang** [resemble-ai/Resemblyzer#34]
when i start to run demo02_diarization.py, 
it shows:
ImportError: cannot import name 'sampling_rate' from 'resemblyzer'

**Comment by zhs105** [comment]
Hi   @liszhang 
How did you solve this problem as I am encountering the same problem?

**Comment by liszhang** [comment]
> Hi @liszhang
> How did you solve this problem as I am encountering the same problem?

opened a new issue

**Comment by liszhang** [comment]
> Hi @liszhang
> How did you solve this problem as I am encountering the same problem?

open a new issue

**Comment by Thierryonre** [comment]
Take a look at issue #39 

Hope this helps :D
