### ISSUE TITLE
ImportError: cannot import name 'sampling_rate'

### ISSUE THREAD

**Issue by i-bond** [resemble-ai/Resemblyzer#39]
Hello! I'm facing an
`ImportError: cannot import name 'sampling_rate'`
when I tried to run the demo02_diarization.py file provided in the example:
`from resemblyzer import sampling_rate`

Could you help me to figure out how to fix this error?

**Comment by Thierryonre** [comment]
Change `from resemblyzer import sampling_rate`
To `from resemblyzer.audio import sampling_rate`

Hope this helps :D

**Comment by i-bond** [comment]
Oh, it works! Thank you 😄
