### ISSUE TITLE
Cannot import "sampling_rate" 

### ISSUE THREAD

**Issue by b-zhang93** [resemble-ai/Resemblyzer#43]
Whenever the line "from resemblyzer import sampling_rate" is run, I get an import error that says I cannot import "sampling_rate". This occurs when I import demo_utils as well because it has this line in its imports. Is there any reason this could be the case?

I am using Google Colab and just installed the resemblyzer package Today (Nov 17/20)

Any help would be appreciated thanks!

**Comment by CorentinJ** [comment]
See #39
