### ISSUE TITLE
New release plans to include latest changes?

### ISSUE THREAD

**Issue by alexteua** [resemble-ai/Resemblyzer#79]
Hi, do you have any plans to do a release on pip? Current version can't be used with newest versions of librosa. The problem seems to be fixed in #71 . Would be great to have an updated version on pip. Thanks!

**Comment by CorentinJ** [comment]
I've made a push, please reopen the issue if you encounter any problem

https://pypi.org/project/Resemblyzer/0.1.2/

**Comment by alexteua** [comment]
Thanks @CorentinJ ! 
I installed a new version via pip, but now getting "ModuleNotFoundError: No module named 'resemblyzer'"

**Comment by Dramalf** [comment]
> 

I met the same problem

**Comment by CorentinJ** [comment]
My apologies, I failed to include the package files in the version. Being in a bit of a rush I didn't bother with testing. I re-released under version 0.13

**Comment by alexteua** [comment]
@CorentinJ works now! Thank you! :)
