### ISSUE TITLE
More information on dataset and training pipeline

### ISSUE THREAD

**Issue by vanIvan** [resemble-ai/Resemblyzer#8]
Hello, thank you for this repository and Real-Time-Voice-Cloning, I'm curious about how exactly you trained this Resemblyzer model, which datasets you used? vox1, vox2, libri or other? If you'd share training scripts it will be very helpful to retrain embeddings for our domain, if it is not under any NDA.

Best regards

Ivan

**Comment by CorentinJ** [comment]
#3

**Comment by vanIvan** [comment]
Sorry, didn't find it! Thanks
