### ISSUE TITLE
Getting different speaker embeddings from same wav file on different machine

### ISSUE THREAD

**Issue by predawnang** [resemble-ai/Resemblyzer#81]
Hi, im planing to use resemblyzer as metric to evaluate voice conversion model, but i find that the speaker embedding genereted from resemblyzer gives different result from one wav file on different machine.

In one machine it gives me 
![image](https://user-images.githubusercontent.com/37857978/236660469-a35a9642-318e-46b5-81e4-c92295f34c05.png)

and in the other it gives me
![image](https://user-images.githubusercontent.com/37857978/236660546-cf2fabb5-e168-41fd-b643-7946b9c446f8.png)

Both machines are ubuntu 18.04.6, the two given embeddings are sightly different at the decimal places.
resamblyzer in both machine is version 0.1.1dev0 installed through pip.

I want to use speaker verification as metric to test my model, but since it gives different result, it's hard to reproduce my result on different machines. Is there a way to make the embedding consistent on different machines? 

Thanks

**Comment by CorentinJ** [comment]
You can expect variations in float precision for torch operations depending on the environment they are running on. These variations are usually no higher than 1e-06. As far as I know, there is no foolproof way to solve this problem without disabling pytorch optimizations. 

You can safely round the embedding down to 5 decimal places, or assume that you will have small floating point errors in your computations and adapt your code in this regard. Numpy and torch have an `all_close` method that might be helpful.

**Comment by predawnang** [comment]
Thank you for your reply, it's helpful.
